function createfigure(X1, XData1, YData1, XMatrix1, YMatrix1, ZMatrix1, XData2, YData2, ZData1)
%CREATEFIGURE(X1, XData1, YData1, XMatrix1, YMatrix1, ZMatrix1, XData2, YData2, ZData1)
%  X1:  vector of x data
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XMATRIX1:  matrix of x data
%  YMATRIX1:  matrix of y data
%  ZMATRIX1:  matrix of z data
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  ZDATA1:  line zdata

%  Auto-generated by MATLAB on 06-Dec-2024 15:31:25

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot3
plot3(X1,X1,X1);

% Create line
line(XData1,YData1,X1,'Tag','head','Parent',axes1,'Marker','o',...
    'Color',[0 0.447 0.741]);

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('Tag','body','Parent',axes1,...
    'Color',[0.85 0.325 0.098],...
    'MaximumNumPoints',1011);

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('Tag','tail','Parent',axes1,...
    'Color',[0.929 0.694 0.125],...
    'MaximumNumPoints',10111);

% Create multiple lines using matrix input to plot3
plot31 = plot3(XMatrix1,YMatrix1,ZMatrix1);
set(plot31(1),'Color',[1 0 0]);
set(plot31(2),'Color',[0 0 1]);

% Create line
line(XData2,YData2,ZData1,'Tag','head','Parent',axes1,'Marker','o',...
    'Color',[0 0.447 0.741]);

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('Tag','body','Parent',axes1,...
    'Color',[0.85 0.325 0.098],...
    'MaximumNumPoints',1011);

% Create matlab.graphics.animation.AnimatedLine
matlab.graphics.animation.AnimatedLine('Tag','tail','Parent',axes1,...
    'Color',[0.929 0.694 0.125],...
    'MaximumNumPoints',10111);

% Create zlabel
zlabel('Z');

% Create ylabel
ylabel('Y');

% Create xlabel
xlabel('X');

% Create title
title('Evolution of Actual Position');

view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'off');
